--- # handlers/docker.yml

- name: enable docker daemon
  systemd: name=docker enabled=yes state=started
  become: true

- name: restart docker daemon
  service: name=docker enabled=yes state=restarted 
  become: true

- name: stop docker services
  systemd: name={{ service_name }} state=stopped
  become: true

- name: start docker services
  systemd: name={{ service_name }} state=started enabled=yes
  become: true

- name: restart docker services
  systemd: name={{ service_name }} state=restarted enabled=yes
  become: true
