---
# handlers file for <%= projectName %>

- name: save iptables
  command: service iptables save
  become: true

- name: enable iptables
  command: systemctl enable iptables
  become: true

- name: restart iptables
  service: name=iptables state=restarted
  become: true

- name: start iptables
  service: name=iptables state=started
  become: true

- name: reload sysctl
  command: sysctl --system
  become: true

- name: daemon reload
  command: systemctl daemon-reload
  args:
    warn: no
  become: true

- name: restart docker daemon
  service: name=docker state=restarted
  become: true

- name: restart docker services
  command: echo "Restarting docker services"
  notify:
  - stop docker services
  - start docker services

- name: stop docker services
  docker_service:
    project_src: "{{ install_path }}"
    state: absent
  become: true

- name: start docker services
  docker_service:
    project_src: "{{ install_path }}"
    state: present
  become: true

- name: migrate
  command: docker-compose run --rm web python manage.py migrate
  args:
    chdir: "{{ install_path }}"
  become: yes

- name: collectstatic
  command: docker-compose run --rm web python manage.py collectstatic --noinput
  args:
    chdir: "{{ install_path }}"
  become: yes
