---
# handlers file for the <%= projectName %> role

- include: firewall.yml

- include: docker.yml

- name: chown data files
  file: path={{ data_dir }} state=directory recurse=yes mode=0700
        owner={{ <%= projectName %>_user }} group={{ <%= projectName %>_group }}
  listen: restart docker services
  become: true

- name: reload sysctl
  command: sysctl --system
  become: true

- name: daemon reload
  command: systemctl daemon-reload
  args:
    warn: no
  become: true
