--- # tasks/docker.yml

- name: install docker-compose config
  template: src=templates/docker-compose.yml.j2 dest={{ install_path }}/docker-compose.yml
  become: true
  notify:
  - restart docker services

- name: install systemd service
  template: src=templates/systemd.service.j2
            dest=/etc/systemd/system/{{ service_name }}.service
            mode=0600 owner=root group=root
  become: true

- name: install pip
  yum: name=python-pip state=present
  become: true

- name: install pip3
  yum: name=python3-pip state=present
  become: true

- name: update pip3 to latest
  pip: name={{ item }} state=latest executable=pip3
  become: true
  with_items:
  - setuptools
  - pip

- name: install docker python bindings
  pip: name={{ item }} state=present executable=pip2
  become: true
  with_items:
  - docker-py==1.10.6
  - docker-compose==1.9.0

- name: ensure docker daemon is running
  systemd: name=docker state=started
  become: true

- name: login to registry
  docker_login: registry={{ docker_registry }} state=present
                username={{ docker_username }} password={{ docker_password }}
  become: true
  changed_when: false
  notify:
  - restart docker services

- name: pull latest repo
  docker_container: name=<%= projectName %> pull=yes image={{ docker_repo }}:{{ docker_tag }}
                    state=present
  become: true
  notify:
  - restart docker services
  - migrate
  - collectstatic

- name: logout of registry
  docker_login: registry={{ docker_registry }} state=absent
  become: true
  notify:
  - restart docker services
