--- # tasks/main.yml file for <%= projectName %>

- include: setup.yml

- include: nginx.yml

- include: docker.yml

- include: firewall.yml
  become: true
  when: "'prod' in group_names or 'test' in group_names"
